# This is a basic workflow to help you get started with Actions

name: gourcer

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Pre Check
      run: ls
    - name: Create video
      run: docker run -v "$(pwd):/results"  --env TITLE="$(head repo)" czerasz/gource "$(head repo)"
    - name: Check
      run: ls
    # - name: Copy creds
    #   env:
    #     CLIENT_SECRETS: ${{ secrets.CLIENT_SECRETS }}
    #     REQUEST_TOKEN: ${{ secrets.REQUEST_TOKEN }}
    #   run: |
    #     echo "$CLIENT_SECRETS" > client_secrets.json
    #     echo "$REQUEST_TOKEN" > request.token
    # - name: Pull yt-upload
    #   run: |
    #     wget 'https://github.com/porjo/youtubeuploader/releases/download/20.04/youtubeuploader_linux_amd64.tar.gz' 
    #     tar -xvzf youtubeuploader_linux_amd64.tar.gz
    - name: Run yt-upload
      run: |
        echo "..$(head repo).."
        echo ">>$(head repo|sed 's|/|-|')<<"
        echo ./youtubeuploader_linux_amd64 -filename "$(head repo|sed 's|/|-|').mp4" -title "Gource visualisation: $(head repo|sed 's|/|-|').mp4 on $(ate '+%Y-%m-%d')" -description 'https://github.com/meain/gourcer' -tags='gource,video,git,github,tech'
