# This is a basic workflow to help you get started with Actions

name: gourcer

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Update repos
      run: |
        sudo apt-get update
    - name: Install gource and ffmpeg
      run: |
        sudo apt-get install -y gource ffmpeg
    - name: Pull a repo
      run: |
        mkdir video_assets && cd video_assets
        git clone https://github.com/meain/dotfiles
    - name: Generate video
      run: |
        gource -f -3840x2160 --camera-mode  track  --file-idle-time 150  --max-file-lag 4 --seconds-per-day 2 --highlight-all-users --output-framerate 30 --output-ppm-stream output.ppm
        ffmpeg -i output.ppm -c:v libx264 -crf 24 -preset veryslow output.mp4
